use std::fmt::{self, Write as _};
use std::path::Path;

use super::{
    CommandStrategy, ExceptionOutcome, Manifest, PairCase, ProvisioningDisposition, ServerCase,
    SmokeDisposition,
};

#[derive(Clone, Copy)]
enum Support {
    Unsupported,
    NotApplicable,
    Supported,
    Limited,
    Failure,
}

impl Support {
    const fn marker(self) -> &'static str {
        match self {
            Self::Unsupported => "✗",
            Self::NotApplicable => "N/A",
            Self::Supported => "✓",
            Self::Limited => "△",
            Self::Failure => "⚠",
        }
    }
}

impl Manifest {
    pub(crate) fn render_server_docs(&self, repository: &Path) -> Result<String, String> {
        let commands = self
            .commands_for(CommandStrategy::LspFixture)
            .collect::<Vec<_>>();
        let mut pairs = self
            .compatible_pair_inventory(&repository.join("data"))?
            .into_iter()
            .collect::<Vec<_>>();
        pairs.sort_by(|left, right| {
            left.server
                .cmp(&right.server)
                .then_with(|| left.language.cmp(&right.language))
        });
        let mut output = String::from(
            "<!-- Generated by `make gen-servers`; do not edit manually. -->\n\n\
             # Server support\n\n\
             Generated from `data/` and `server-support/`. No language server is run while\n\
             generating this document.\n\n\
             The matrix records support evidence declared by the repository configuration. It is\n\
             not a live probe and does not guarantee identical behavior across every project,\n\
             platform, or server version.\n\n\
             - **✓**: configured support\n\
             - **△**: supported with a documented result limitation\n\
             - **⚠**: documented command failure\n\
             - **✗**: the measured capabilities do not support the operation\n\
             - **N/A**: unavailable to the suite or not inferable from advertised capabilities\n\n\
             In the Mason column, **✓** means automatic download is configured and **N/A** means\n\
             it is unavailable.\n\n\
             | Server | Language | Mason |",
        );
        for command in &commands {
            write!(output, " `{command}` |").map_err(render_error)?;
        }
        output.push_str("\n| --- | --- | --- |");
        for _ in &commands {
            output.push_str(" --- |");
        }
        output.push('\n');

        for key in pairs {
            let server = self
                .servers
                .iter()
                .find(|server| server.id == key.server)
                .ok_or_else(|| format!("support matrix has unknown server {:?}", key.server))?;
            let pair = self
                .pairs
                .iter()
                .find(|pair| pair.language == key.language && pair.server == key.server);
            let mason = match server.provisioning {
                ProvisioningDisposition::Download { .. } => "✓",
                ProvisioningDisposition::Excluded { .. } => "N/A",
            };
            write!(
                output,
                "| `{}` | `{}` | {mason} |",
                key.server, key.language
            )
            .map_err(render_error)?;
            for command in &commands {
                let support =
                    support_for(pair, server, &key.language, command).ok_or_else(|| {
                        format!(
                            "support matrix has no verdict for {}/{} command {command}",
                            key.language, key.server
                        )
                    })?;
                write!(output, " {} |", support.marker()).map_err(render_error)?;
            }
            output.push('\n');
        }
        Ok(output)
    }
}

fn support_for(
    pair: Option<&PairCase>,
    server: &ServerCase,
    language: &str,
    command: &str,
) -> Option<Support> {
    if matches!(
        server.provisioning,
        ProvisioningDisposition::Excluded { .. }
    ) {
        return Some(Support::NotApplicable);
    }
    if server.owner_language == language && server.capability_is_unavailable() {
        return Some(Support::NotApplicable);
    }
    if server.owner_language == language
        && let Some(operations) = server.capability_operations()
    {
        return Some(support_from_capabilities(operations, command));
    }
    let smoke = pair.and_then(|pair| pair.smoke.as_ref())?;
    Some(match smoke {
        SmokeDisposition::Queries {
            supported_operations,
            exceptions,
            ..
        } => support_from_operations(
            supported_operations,
            exceptions,
            command,
            Support::Unsupported,
        ),
        SmokeDisposition::Capabilities {
            supported_operations,
            ..
        } => support_from_capabilities(supported_operations, command),
        SmokeDisposition::Excluded { .. } => Support::NotApplicable,
    })
}

fn support_from_capabilities(operations: &[super::QueryKind], command: &str) -> Support {
    let absent = if matches!(command, "diagnostics" | "build-index") {
        Support::NotApplicable
    } else {
        Support::Unsupported
    };
    support_from_operations(operations, &[], command, absent)
}

fn support_from_operations(
    operations: &[super::QueryKind],
    exceptions: &[super::query_case::QueryException],
    command: &str,
    absent: Support,
) -> Support {
    if !operations
        .iter()
        .any(|operation| operation.command_name() == command)
    {
        return absent;
    }
    exceptions
        .iter()
        .find(|exception| exception.command.command_name() == command)
        .map_or(Support::Supported, |exception| match exception.outcome {
            ExceptionOutcome::EmptyMatches | ExceptionOutcome::VariableMatches => Support::Limited,
            ExceptionOutcome::Failure => Support::Failure,
        })
}

fn render_error(error: fmt::Error) -> String {
    format!("failed to render server support documentation: {error}")
}
