use super::*;
use crate::repository_root;

fn first_query_contract(
    manifest: &mut Manifest,
) -> (&mut Vec<QueryKind>, &mut Vec<query_case::QueryException>) {
    manifest
        .pairs
        .iter_mut()
        .find_map(|pair| match pair.smoke.as_mut()? {
            SmokeDisposition::Queries {
                supported_operations,
                exceptions,
                ..
            } => Some((supported_operations, exceptions)),
            SmokeDisposition::Capabilities { .. } | SmokeDisposition::Excluded { .. } => None,
        })
        .expect("manifest should contain a queries smoke case")
}

fn validation_error(expectation: &str, mutate: impl FnOnce(&mut Manifest)) -> String {
    let mut manifest = Manifest::load().expect("E2E manifest should parse");
    mutate(&mut manifest);
    manifest.validate(repository_root()).expect_err(expectation)
}

fn first_capability_contract(manifest: &mut Manifest) -> &mut Vec<QueryKind> {
    manifest
        .pairs
        .iter_mut()
        .find_map(|pair| match pair.smoke.as_mut()? {
            SmokeDisposition::Capabilities {
                supported_operations,
                ..
            } => Some(supported_operations),
            SmokeDisposition::Queries { .. } | SmokeDisposition::Excluded { .. } => None,
        })
        .expect("manifest should contain a capabilities smoke case")
}

#[test]
fn server_docs_cover_every_compatible_pair() {
    let manifest = Manifest::load_validated(repository_root()).expect("manifest should validate");
    let document = manifest
        .render_server_docs(repository_root())
        .expect("server documentation should render");
    let rows = document
        .lines()
        .filter(|line| line.starts_with("| `"))
        .collect::<Vec<_>>();

    assert_eq!(rows.len(), 849);
    assert!(document.starts_with("<!-- Generated by `make gen-servers`"));
    assert!(
        !document
            .lines()
            .any(|line| line.starts_with("| `") && line.contains('—'))
    );
    assert!(document.contains("| N/A |"));
    assert!(document.contains("| ✗ |"));
    assert!(
        rows.first()
            .is_some_and(|row| row.starts_with("| `ada_ls` | `ada` |"))
    );
    assert!(
        rows.iter()
            .any(|row| row.starts_with("| `gopls` | `go` |") && row.contains('⚠'))
    );
}

#[test]
fn manifest_rejects_duplicate_supported_operations() {
    let error = validation_error("duplicate supported operation should fail", |manifest| {
        let (supported_operations, _) = first_query_contract(manifest);
        supported_operations.push(supported_operations[0]);
    });

    assert!(error.contains("repeats a supported operation"));
}

#[test]
fn manifest_requires_operations_without_advertised_capabilities() {
    let error = validation_error("required operation should fail", |manifest| {
        let (supported_operations, _) = first_query_contract(manifest);
        supported_operations.retain(|operation| *operation != QueryKind::BuildIndex);
    });

    assert!(error.contains("must support build-index"));
}

#[test]
fn manifest_requires_exception_operations_to_be_supported() {
    let error = validation_error("unsupported exception operation should fail", |manifest| {
        let (supported_operations, exceptions) = first_query_contract(manifest);
        let exception = exceptions
            .first()
            .expect("first query case should contain an exception")
            .command;
        supported_operations.retain(|operation| *operation != exception);
    });

    assert!(error.contains("requires its operation to be supported"));
}

#[test]
fn capability_contract_requires_server_capabilities() {
    let error = validation_error("capability baseline should fail", |manifest| {
        first_capability_contract(manifest)
            .retain(|operation| *operation != QueryKind::ServerCapabilities);
    });

    assert!(error.contains("must support server-capabilities"));
}

#[test]
fn server_capability_contract_validates_deadlines() {
    let error = validation_error("capability deadline should fail", |manifest| {
        let server = manifest
            .servers
            .iter_mut()
            .find(|server| server.id == "clangd")
            .expect("clangd provisioning should exist");
        server.coverage = provisioning_case::ServerCoverage::Capabilities {
            supported_operations: vec![QueryKind::ServerCapabilities],
            lsp_timeout_seconds: Some(0),
            deadline_seconds: None,
        };
    });

    assert!(error.contains("deadlines"));
}
