language:
  id: dockerfile
  kind: metadata
  project: playground/dockerfile
pairs:
  - language: dockerfile
    server: docker_language_server
    smoke:
      status: capabilities
      supported-operations:
        - server-capabilities
        - format
        - list-symbols
        - list-functions
        - definition
  - language: dockerfile
    server: dockerls
    smoke:
      status: capabilities
      supported-operations:
        - server-capabilities
        - format
        - list-symbols
        - list-functions
        - definition
  - language: dockerfile
    server: snyk_ls
    smoke:
      status: capabilities
      supported-operations:
        - server-capabilities
